version: '3.9'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                LINUX_USER_ID: ${LINUX_USER_ID}
        environment:
            XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_REMOTE_PORT}
            PHP_IDE_CONFIG: serverName=${IDE_SERVER_NAME}
        networks:
            - phplvl2
        tty: true
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./:/srv/app

networks:
    phplvl2:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.245.0/28
