#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use function Differ\Differ\genDiff;

$doc = <<<DOC
gendiff -h

Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help                     Show this screen
  -v --version                  Show version
  --format <fmt>                Report format [default: stylish]
DOC;

$args = Docopt::handle($doc, ['version' => 'Diff Generator 0.1.0']);

echo genDiff($args['<firstFile>'], $args['<secondFile>']);
