name: tests

on:
    push:
        branches:
            - '**'
        tags:
            - '**'

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  coverage: xdebug

            - name: Install dependencies
              run: composer install

            - name: Run linter
              run: make lint

            - name: Run tests
              run: make test
